server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS256

superuser-password: ${SUPERUSER_PASSWORD}
jwt-secret-key: ${JWT_SECRET_KEY}