spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET_KEY}