ALTER TABLE "competitions" DROP CONSTRAINT IF EXISTS "competitions_cup_id_fkey";
ALTER TABLE "individual_groups" DROP CONSTRAINT IF EXISTS "individual_groups_competition_id_fkey";
ALTER TABLE "competitor_competition_details" DROP CONSTRAINT IF EXISTS "competitor_competition_details_competition_id_fkey";
ALTER TABLE "competitor_competition_details" DROP CONSTRAINT IF EXISTS "competitor_competition_details_competitor_id_fkey";
ALTER TABLE "competitor_group_details" DROP CONSTRAINT IF EXISTS "competitor_group_details_group_id_fkey";
ALTER TABLE "competitor_group_details" DROP CONSTRAINT IF EXISTS "competitor_group_details_competitor_id_fkey";
ALTER TABLE "qualifications" DROP CONSTRAINT IF EXISTS "qualifications_group_id_fkey";
ALTER TABLE "qualification_sections" DROP CONSTRAINT IF EXISTS "qualification_sections_group_id_fkey";
ALTER TABLE "qualification_sections" DROP CONSTRAINT IF EXISTS "qualification_sections_competitor_id_fkey";
ALTER TABLE "qualification_rounds" DROP CONSTRAINT IF EXISTS "qualification_rounds_section_id_fkey";
ALTER TABLE "qualification_rounds" DROP CONSTRAINT IF EXISTS "qualification_rounds_range_group_id_fkey";
ALTER TABLE "quarterfinals" DROP CONSTRAINT IF EXISTS "quarterfinals_group_id_fkey";
ALTER TABLE "quarterfinals" DROP CONSTRAINT IF EXISTS "quarterfinals_sparring1_id_fkey";
ALTER TABLE "quarterfinals" DROP CONSTRAINT IF EXISTS "quarterfinals_sparring2_id_fkey";
ALTER TABLE "quarterfinals" DROP CONSTRAINT IF EXISTS "quarterfinals_sparring3_id_fkey";
ALTER TABLE "quarterfinals" DROP CONSTRAINT IF EXISTS "quarterfinals_sparring4_id_fkey";
ALTER TABLE "semifinals" DROP CONSTRAINT IF EXISTS "semifinals_group_id_fkey";
ALTER TABLE "semifinals" DROP CONSTRAINT IF EXISTS "semifinals_sparring5_id_fkey";
ALTER TABLE "semifinals" DROP CONSTRAINT IF EXISTS "semifinals_sparring6_id_fkey";
ALTER TABLE "finals" DROP CONSTRAINT IF EXISTS "finals_group_id_fkey";
ALTER TABLE "finals" DROP CONSTRAINT IF EXISTS "finals_sparring_gold_id_fkey";
ALTER TABLE "finals" DROP CONSTRAINT IF EXISTS "finals_sparring_bronze_id_fkey";
ALTER TABLE "sparrings" DROP CONSTRAINT IF EXISTS "sparrings_top_place_id_fkey";
ALTER TABLE "sparrings" DROP CONSTRAINT IF EXISTS "sparrings_bot_place_id_fkey";
ALTER TABLE "sparring_places" DROP CONSTRAINT IF EXISTS "sparring_places_competitor_id_fkey";
ALTER TABLE "sparring_places" DROP CONSTRAINT IF EXISTS "sparring_places_range_group_id_fkey";
ALTER TABLE "shoot_outs" DROP CONSTRAINT IF EXISTS "shoot_outs_place_id_fkey";
ALTER TABLE "ranges" DROP CONSTRAINT IF EXISTS "ranges_group_id_fkey";
ALTER TABLE "shots" DROP CONSTRAINT IF EXISTS "shots_range_id_fkey";

DROP TABLE IF EXISTS "shots";
DROP TABLE IF EXISTS "ranges";
DROP TABLE IF EXISTS "range_groups";
DROP TABLE IF EXISTS "shoot_outs";
DROP TABLE IF EXISTS "sparring_places";
DROP TABLE IF EXISTS "sparrings";
DROP TABLE IF EXISTS "finals";
DROP TABLE IF EXISTS "semifinals";
DROP TABLE IF EXISTS "quarterfinals";
DROP TABLE IF EXISTS "qualification_rounds";
DROP TABLE IF EXISTS "qualification_sections";
DROP TABLE IF EXISTS "qualifications";
DROP TABLE IF EXISTS "competitor_group_details";
DROP TABLE IF EXISTS "competitor_competition_details";
DROP TABLE IF EXISTS "individual_groups";
DROP TABLE IF EXISTS "competitions";
DROP TABLE IF EXISTS "cups";
DROP TABLE IF EXISTS "competitors";

DROP TYPE IF EXISTS "group_state";
DROP TYPE IF EXISTS "gender";
DROP TYPE IF EXISTS "bow_class";
DROP TYPE IF EXISTS "sports_rank";
DROP TYPE IF EXISTS "sparring_state";
DROP TYPE IF EXISTS "competition_stage";
DROP TYPE IF EXISTS "range_type";