CREATE TYPE "group_state" AS ENUM (
    'created',
    'qualification_start',
    'qualification_end',
    'quarterfinal_start',
    'semifinal_start',
    'final_start',
    'completed'
    );

CREATE TYPE "gender" AS ENUM (
    'male',
    'female'
    );

CREATE TYPE "bow_class" AS ENUM (
    'classic',
    'block',
    'classic_newbie',
    '3D_classic',
    '3D_compound',
    '3D_long',
    'peripheral',
    'peripheral_with_ring'
    );

CREATE TYPE "sports_rank" AS ENUM (
    'merited_master',
    'master_international',
    'master',
    'candidate_for_master',
    'first_class',
    'second_class',
    'third_class'
    );

CREATE TYPE "sparring_state" AS ENUM (
    'ongoing',
    'top_win',
    'bot_win'
    );

CREATE TYPE "competition_stage" AS ENUM (
    'I',
    'II',
    'III',
    'F'
    );

CREATE TYPE "range_type" AS ENUM (
    '1-10',
    '6-10'
    );

CREATE TABLE "cups" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "title" varchar(256) NOT NULL,
                        "address" varchar(256),
                        "season" char(9)
);

CREATE TABLE "competitions" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "cup_id" bigint NOT NULL,
                                "stage" competition_stage NOT NULL,
                                "start_date" date,
                                "end_date" date,
                                "is_ended" bool NOT NULL DEFAULT false
);

CREATE TABLE "individual_groups" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "competition_id" bigint NOT NULL,
                                     "bow" bow_class NOT NULL,
                                     "identity" gender,
                                     "state" group_state NOT NULL DEFAULT 'created'
);

CREATE TABLE "competitor_competition_details" (
                                                  "competition_id" bigint  UNIQUE,
                                                  "competitor_id" bigint  UNIQUE,
                                                  "is_active" bool NOT NULL DEFAULT true,
                                                  "created_at" timestamptz DEFAULT (now()),
                                                  PRIMARY KEY ("competition_id", "competitor_id")
);

CREATE TABLE "competitor_group_details" (
                                            "group_id" bigint  UNIQUE,
                                            "competitor_id" bigint  UNIQUE,
                                            PRIMARY KEY ("group_id", "competitor_id")
);

CREATE TABLE "qualifications" (
                                  "group_id" bigint PRIMARY KEY,
                                  "distance" varchar(10) NOT NULL,
                                  "round_count" smallint NOT NULL
);

CREATE TABLE "qualification_sections" (
                                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "group_id" bigint NOT NULL,
                                          "competitor_id" bigint NOT NULL,
                                          "place" smallint
);

CREATE TABLE "qualification_rounds" (
                                        "section_id" bigint,
                                        "round_ordinal" smallint,
                                        "is_active" bool NOT NULL DEFAULT false,
                                        "range_group_id" bigint NOT NULL,
                                        PRIMARY KEY ("section_id", "round_ordinal")
);

CREATE TABLE "quarterfinals" (
                                 "group_id" bigint PRIMARY KEY,
                                 "sparring1_id" bigint,
                                 "sparring2_id" bigint,
                                 "sparring3_id" bigint,
                                 "sparring4_id" bigint
);

CREATE TABLE "semifinals" (
                              "group_id" bigint PRIMARY KEY,
                              "sparring5_id" bigint,
                              "sparring6_id" bigint
);

CREATE TABLE "finals" (
                          "group_id" bigint PRIMARY KEY,
                          "sparring_gold_id" bigint,
                          "sparring_bronze_id" bigint
);

CREATE TABLE "sparrings" (
                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "top_place_id" bigint,
                             "bot_place_id" bigint,
                             "state" sparring_state NOT NULL DEFAULT 'ongoing'
);

CREATE TABLE "sparring_places" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "competitor_id" bigint NOT NULL,
                                   "range_group_id" bigint
);

CREATE TABLE "shoot_outs" (
                              "place_id" bigint PRIMARY KEY,
                              "score" varchar(2),
                              "priority" bool
);

CREATE TABLE "range_groups" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "ranges_max_count" smallint NOT NULL,
                                "range_size" smallint NOT NULL,
                                "type" range_type NOT NULL
);

CREATE TABLE "ranges" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "group_id" bigint NOT NULL,
                          "range_ordinal" smallint NOT NULL,
                          "is_active" bool NOT NULL DEFAULT false
);

CREATE TABLE "shots" (
                         "range_id" bigint,
                         "shot_ordinal" smallint,
                         "score" varchar(2),
                         PRIMARY KEY ("range_id", "shot_ordinal")
);

CREATE TABLE "competitors" (
                               "id" bigint PRIMARY KEY,
                               "full_name" varchar(32) NOT NULL,
                               "birth_date" date NOT NULL,
                               "identity" gender NOT NULL,
                               "bow" bow_class,
                               "rank" sports_rank,
                               "region" varchar(256),
                               "federation" varchar(256),
                               "club" varchar(256)
);

CREATE UNIQUE INDEX ON "competitions" ("cup_id", "stage");

CREATE UNIQUE INDEX ON "individual_groups" ("competition_id", "bow", "identity");

CREATE UNIQUE INDEX ON "qualification_sections" ("group_id", "competitor_id");

CREATE UNIQUE INDEX ON "ranges" ("group_id", "range_ordinal");

CREATE INDEX ON "ranges" USING HASH ("group_id");

CREATE INDEX ON "shots" USING HASH ("range_id");

COMMENT ON COLUMN "shoot_outs"."score" IS 'numbers 1-10 and M, X';

COMMENT ON COLUMN "shoot_outs"."priority" IS 'signifies +/- sign after shoot-out if necessary';

COMMENT ON COLUMN "shots"."score" IS 'numbers 1-10 and M, X';

ALTER TABLE "competitions" ADD FOREIGN KEY ("cup_id") REFERENCES "cups" ("id");

ALTER TABLE "individual_groups" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id");

ALTER TABLE "competitor_competition_details" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions"("id");
ALTER TABLE "competitor_competition_details" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");

ALTER TABLE "competitor_group_details" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");

ALTER TABLE "competitor_group_details" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");

ALTER TABLE "qualifications" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");

ALTER TABLE "qualification_sections" ADD FOREIGN KEY ("group_id") REFERENCES "qualifications" ("group_id");

ALTER TABLE "qualification_sections" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");

ALTER TABLE "qualification_rounds" ADD FOREIGN KEY ("section_id") REFERENCES "qualification_sections" ("id");

ALTER TABLE "qualification_rounds" ADD FOREIGN KEY ("range_group_id") REFERENCES "range_groups" ("id");

ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");

ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring1_id") REFERENCES "sparrings" ("id");

ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring2_id") REFERENCES "sparrings" ("id");

ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring3_id") REFERENCES "sparrings" ("id");

ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring4_id") REFERENCES "sparrings" ("id");

ALTER TABLE "semifinals" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");

ALTER TABLE "semifinals" ADD FOREIGN KEY ("sparring5_id") REFERENCES "sparrings" ("id");

ALTER TABLE "semifinals" ADD FOREIGN KEY ("sparring6_id") REFERENCES "sparrings" ("id");

ALTER TABLE "finals" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");

ALTER TABLE "finals" ADD FOREIGN KEY ("sparring_gold_id") REFERENCES "sparrings" ("id");

ALTER TABLE "finals" ADD FOREIGN KEY ("sparring_bronze_id") REFERENCES "sparrings" ("id");

ALTER TABLE "sparrings" ADD FOREIGN KEY ("top_place_id") REFERENCES "sparring_places" ("id");

ALTER TABLE "sparrings" ADD FOREIGN KEY ("bot_place_id") REFERENCES "sparring_places" ("id");

ALTER TABLE "sparring_places" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");

ALTER TABLE "sparring_places" ADD FOREIGN KEY ("range_group_id") REFERENCES "range_groups" ("id");

ALTER TABLE "shoot_outs" ADD FOREIGN KEY ("place_id") REFERENCES "sparring_places" ("id");

ALTER TABLE "ranges" ADD FOREIGN KEY ("group_id") REFERENCES "range_groups" ("id");

ALTER TABLE "shots" ADD FOREIGN KEY ("range_id") REFERENCES "ranges" ("id");
