-- Создание типов данных
CREATE TYPE "group_state" AS ENUM (
  'created',
  'qualification_start',
  'qualification_end',
  'finals_start',
  'finals_end'
);

CREATE TYPE "gender" AS ENUM (
  'male',
  'female'
);

CREATE TYPE "bow_class" AS ENUM (
  'classic',
  'block',
  'classic_newbie',
  '3D_classic',
  '3D_compound',
  '3D_long',
  'peripheral',
  'peripheral_with_ring'
);

CREATE TYPE "sports_rank" AS ENUM (
  'merited_master',
  'master_international',
  'master',
  'candidate_for_master',
  'first_class',
  'second_class',
  'third_class'
);

CREATE TYPE "sparring_state" AS ENUM (
  'ongoing',
  'top_win',
  'bot_win'
);

CREATE TYPE "competition_stage" AS ENUM (
  'I',
  'II',
  'III',
  'F'
);

-- Создание таблиц
CREATE TABLE "cups" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "title" varchar(256) NOT NULL,
                        "address" varchar(256),
                        "season" char(9)
);

CREATE TABLE "competitions" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "cup_id" bigint NOT NULL,
                                "stage" competition_stage NOT NULL,
                                "start_date" date,
                                "end_date" date,
                                "is_ended" bool NOT NULL DEFAULT false
);

CREATE TABLE "competitors" (
                               "id" bigint PRIMARY KEY,
                               "full_name" varchar(32) NOT NULL
);

CREATE TABLE "competitor_competition_details" (
                                                  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  "competition_id" bigint NOT NULL,
                                                  "competitor_id" bigint NOT NULL,
                                                  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "individual_groups" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "competition_id" bigint NOT NULL,
                                     "bow" bow_class NOT NULL,
                                     "identity" gender,
                                     "state" group_state NOT NULL DEFAULT 'created'
);

CREATE TABLE "competitor_group_details" (
                                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            "group_id" bigint NOT NULL,
                                            "competitor_id" bigint NOT NULL
);

CREATE TABLE "qualifications" (
                                  "group_id" bigint PRIMARY KEY,
                                  "distance" varchar(10) NOT NULL,
                                  "round_count" smallint NOT NULL
);

CREATE TABLE "qualification_sections" (
                                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "group_id" bigint NOT NULL,
                                          "competitor_id" bigint NOT NULL,
                                          "place" smallint
);

CREATE TABLE "qualification_rounds" (
                                        "section_id" bigint,
                                        "round_number" smallint,
                                        "range_group_id" bigint,
                                        PRIMARY KEY ("section_id", "round_number")
);

CREATE TABLE "quarterfinals" (
                                 "group_id" bigint PRIMARY KEY,
                                 "sparring1_id" bigint,
                                 "sparring2_id" bigint,
                                 "sparring3_id" bigint,
                                 "sparring4_id" bigint
);

CREATE TABLE "semifinals" (
                              "group_id" bigint PRIMARY KEY,
                              "sparring5_id" bigint,
                              "sparring6_id" bigint
);

CREATE TABLE "finals" (
                          "group_id" bigint PRIMARY KEY,
                          "sparring_gold_id" bigint,
                          "sparring_bronze_id" bigint
);

CREATE TABLE "sparrings" (
                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "top_place_id" bigint,
                             "bot_place_id" bigint,
                             "state" sparring_state NOT NULL DEFAULT 'ongoing'
);

CREATE TABLE "sparring_places" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "competitor_id" bigint NOT NULL,
                                   "range_group_id" bigint
);

CREATE TABLE "shoot_outs" (
                              "place_id" bigint PRIMARY KEY,
                              "score" varchar(2),
                              "priority" bool
);

CREATE TABLE "range_groups" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "ranges_count" smallint NOT NULL,
                                "range_size" smallint NOT NULL
);

CREATE TABLE "ranges" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "group_id" bigint NOT NULL,
                          "range_number" smallint NOT NULL,
                          "is_completed" bool NOT NULL DEFAULT false
);

CREATE TABLE "shots" (
                         "range_id" bigint,
                         "shot_number" smallint,
                         "score" varchar(2),
                         PRIMARY KEY ("range_id", "shot_number")
);

CREATE TABLE "competitors_detail" (
                                      "competitor_id" bigint PRIMARY KEY,
                                      "birth_date" date,
                                      "identity" gender,
                                      "bow" bow_class,
                                      "rank" sports_rank,
                                      "region" varchar(256),
                                      "federation" varchar(256),
                                      "club" varchar(256)
);

-- Создание индексов
CREATE UNIQUE INDEX "competitions_cup_id_stage_unique" ON "competitions" ("cup_id", "stage");
CREATE UNIQUE INDEX "individual_groups_competition_id_bow_identity_unique" ON "individual_groups" ("competition_id", "bow", "identity");
CREATE INDEX "individual_groups_competition_id_hash" ON "individual_groups" USING HASH ("competition_id");
CREATE INDEX "sparring_places_competitor_id_hash" ON "sparring_places" USING HASH ("competitor_id");
CREATE UNIQUE INDEX "ranges_group_id_range_number_unique" ON "ranges" ("group_id", "range_number");
CREATE INDEX "ranges_group_id_hash" ON "ranges" USING HASH ("group_id");
CREATE INDEX "shots_range_id_hash" ON "shots" USING HASH ("range_id");

-- Комментарии
COMMENT ON COLUMN "shoot_outs"."score" IS 'numbers 1-10 and M, X';
COMMENT ON COLUMN "shots"."score" IS 'numbers 1-10 and M, X';

-- Внешние ключи
ALTER TABLE "competitions" ADD FOREIGN KEY ("cup_id") REFERENCES "cups" ("id");
ALTER TABLE "individual_groups" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id");
ALTER TABLE "competitor_competition_details" ADD FOREIGN KEY ("competition_id") REFERENCES "competitions" ("id");
ALTER TABLE "competitor_competition_details" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");
ALTER TABLE "competitor_group_details" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");
ALTER TABLE "competitor_group_details" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");
ALTER TABLE "qualifications" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");
ALTER TABLE "qualification_sections" ADD FOREIGN KEY ("group_id") REFERENCES "qualifications" ("group_id");
ALTER TABLE "qualification_sections" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");
ALTER TABLE "qualification_rounds" ADD FOREIGN KEY ("section_id") REFERENCES "qualification_sections" ("id");
ALTER TABLE "qualification_rounds" ADD FOREIGN KEY ("range_group_id") REFERENCES "range_groups" ("id");
ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");
ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring1_id") REFERENCES "sparrings" ("id");
ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring2_id") REFERENCES "sparrings" ("id");
ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring3_id") REFERENCES "sparrings" ("id");
ALTER TABLE "quarterfinals" ADD FOREIGN KEY ("sparring4_id") REFERENCES "sparrings" ("id");
ALTER TABLE "semifinals" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");
ALTER TABLE "semifinals" ADD FOREIGN KEY ("sparring5_id") REFERENCES "sparrings" ("id");
ALTER TABLE "semifinals" ADD FOREIGN KEY ("sparring6_id") REFERENCES "sparrings" ("id");
ALTER TABLE "finals" ADD FOREIGN KEY ("group_id") REFERENCES "individual_groups" ("id");
ALTER TABLE "finals" ADD FOREIGN KEY ("sparring_gold_id") REFERENCES "sparrings" ("id");
ALTER TABLE "finals" ADD FOREIGN KEY ("sparring_bronze_id") REFERENCES "sparrings" ("id");
ALTER TABLE "sparrings" ADD FOREIGN KEY ("top_place_id") REFERENCES "sparring_places" ("id");
ALTER TABLE "sparrings" ADD FOREIGN KEY ("bot_place_id") REFERENCES "sparring_places" ("id");
ALTER TABLE "sparring_places" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");
ALTER TABLE "sparring_places" ADD FOREIGN KEY ("range_group_id") REFERENCES "range_groups" ("id");
ALTER TABLE "shoot_outs" ADD FOREIGN KEY ("place_id") REFERENCES "sparring_places" ("id");
ALTER TABLE "ranges" ADD FOREIGN KEY ("group_id") REFERENCES "range_groups" ("id");
ALTER TABLE "shots" ADD FOREIGN KEY ("range_id") REFERENCES "ranges" ("id");
ALTER TABLE "competitors_detail" ADD FOREIGN KEY ("competitor_id") REFERENCES "competitors" ("id");